version: '2'
services:
    springio-app:
        image: springio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springio-mysql:3306/springio?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=springio-elasticsearch:9300
        ports:
            - 8080:8080
    springio-mysql:
        extends:
            file: mysql.yml
            service: springio-mysql
    springio-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: springio-elasticsearch
